---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
  values:
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: secrets
            key: cloudflare_api_token
    sources:
      - service
      - ingress
    provider: cloudflare
    domainFilters:
      - hef.wtf
    policy: sync
    txtOwnerId: external-dns
    extraArgs:
      - --cloudflare-proxied
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi