apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: external-dns
stringData:
    cloudflare_api_token: ENC[AES256_GCM,data:36peNbO7fVhxpQBY4grMx5HnqnAHgB7gdJ7AKh2Wb8nccOKiPRVOjg==,iv:G95lMTNorUfudWbcoNCW5KmycE2ugY2bvds2UoPofRA=,tag:BsZ6COlQchV5lPiHcH3fhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rlrtsx9gye40ewemdenax4phnr4jz5r5rkujn2klvjfpyhpqsqxs6wwjxq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLR1VKc1BjRjJhd3RDb0dk
            am5ITE13bnc3dkd0NWs5Vm1Ma0kyNDdFaVVrClRJaVpXRGFTM0V3Nmo1Z3krdlk3
            dUJRaTJieEFIdTlJVjJjTHAwQ1ZnQlEKLS0tIFVIUlZjdG9DYVFvVzFJYkd5V3Fp
            NjBFbHNOcFE5MDZrODhkcVBVbjF1a1kK/7E/An7NeZdQ9VkzTXhMgAdGT9F9KvbQ
            gvzQz10H2dVN9ADst7vJXwhdg6R5U2bPv43dfox/p4/5GEsGw9ZaTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-29T01:50:50Z"
    mac: ENC[AES256_GCM,data:B95l0ZPrU6iY/o6eTqHjdP0Z4KTIxD+g1FqimZ1ulwlboWJZTO0hhca28bKu/Moq+J+Lxy2X6R7JJT9P3CRrRM95pYMsKhgGiLTRrVezP1wCDUm3GOOue6HRmSJ7KNwjkHIPrDNUrjbVoH+4xdbE0Rf6yA50YcpfO/AYzeBbvrQ=,iv:NF2i/pN50u1ph3FzcIr+rI/SG/F5fczb8Ab0/7MkW+Y=,tag:2RsjCI7oCj2KsJZkaUU9fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
