version: '3'

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/provision/ansible"

env:
  KUBECONFIG: "{{.PROJECT_DIR}}/provision/kubeconfig"

tasks:
  hello: "hello, world!"
  newconfig:
    desc: Generate ~/.kube/newconfig
    vars:
      HOME:
        sh: echo $HOME
    env:
      KUBECONFIG: "{{.PROJECT_DIR}}/provision/kubeconfig:{{.HOME}}/.kube/config"
    cmds:
      - sed -i '' -e 's/127.0.0.1/142.47.218.5/g' {{.PROJECT_DIR}}/provision/kubeconfig
      - sed -i '' -e 's/default/cac-cluster/g' {{.PROJECT_DIR}}/provision/kubeconfig
      - echo ${KUBECONFIG}
      - kubectl config view --flatten > ~/.kube/newconfig
      #- bcomp ~/.kube/config ~/.kube/newconfig


includes:
  ansible: .taskfiles/ansible.yml
  flux: .taskfiles/flux.yml
  terraform: .taskfiles/terraform.yml
