version: '3'

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/provision/ansible"

tasks:
  hello: "hello, world!"

includes:
  ansible: .taskfiles/ansible.yml
