apiVersion: v1
kind: Secret
metadata:
    name: traefik-sso
    namespace: traefik
stringData:
    PROVIDERS_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:YyeFIm7UlqtAph9De+YQTfLIkf5S2mGyRS7MYx4ECWEjhHzQaHT4LI38IzUR2LpCSAp0hLiO6YVKjzeY88XssHVcFFIuGqik,iv:Lc0QtFL7QgQOsapGxkv3a1bQQTrwuIbEFNlWYGf895Q=,tag:pXqQEMwmBEbF6DyczBEnhg==,type:str]
    PROVIDERS_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:oky1l2Y1Oh2Yo6Bxj6c15Yp1i4j0xFbrDL3qlrkNRuFPMBQ=,iv:IP+Xowi2saR4xiG9kTOe1O01QZeVimzTMlYQ25Xs/6M=,tag:pbzVCNgzE+5Ksslb5oX9Iw==,type:str]
    SECRET: ENC[AES256_GCM,data:UAgIeMVX2jk4W8ywkxDnBj4EPDu85FK7ATumuTjIb7c=,iv:BZtRpYdmtxwLe9ku0Ka2nkm3ctv/sCcHlVLHC2ewRDE=,tag:FzS6AvZZwt5R8u5RGmO63w==,type:str]
    WHITELIST: ENC[AES256_GCM,data:qUV74fHVdF5Ltm14pm7+JvJ5//3+2Plcz1OrLiO3tnuv3V/f29EyBI9d,iv:akC9tr9pa5NB8k+G8PywRWxG+nkjSNHvdPrc+j6VVCI=,tag:/RLFlvUiXxrQI2k/yTMg5Q==,type:str]
    COOKIE_DOMAIN: ENC[AES256_GCM,data:QB/2FK5L/w==,iv:aRDuOr98OQIooQMe/5WdRMwWWJERkY1QyO4p3IHuxd8=,tag:JKu6kGv87ErECG8po3MDfw==,type:str]
    AUTH_HOST: ENC[AES256_GCM,data:gl0UQYDeeQ==,iv:TEIFPCkiY00bkcgaMUJwSQNHJEJWD7cmUPJPR+HHGRo=,tag:Lz+XvW0S6uMAlkfZI5DWig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rlrtsx9gye40ewemdenax4phnr4jz5r5rkujn2klvjfpyhpqsqxs6wwjxq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRTljdzljVjkyVEd0TDcw
            ckY5cnhWS1loZkdpUkpYaEE1UWhvQzlKcmxvCjI1NmhXQzFTR3ZUUnkrN1ozWUZM
            ZmNueDdHYVl2N2lDVXdvTmdrWk9ncVkKLS0tIFJMUy9jZjFCUzZmdzFWSGtBQ1Nt
            UzlMbXVtdDN3YXFSN3A2VzQ2Z2dienMKhbQLf1nU7fg9G5xrRrX8wp2Ylcu4c72D
            1XMaEZ/HZcvj8GKC4qC9by6Wt+Nt5iDrAEbPUKaONY2rpFLN9kSaHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T05:39:59Z"
    mac: ENC[AES256_GCM,data:trZnAzokqbdzbxMDoFC3UWOWHZ34rDDMUsGaq3TwU66s45Lf2wlGxQNGaVBBTeq+hn4fDUC+UUVwh1z7ws0QwBTANHgS0Dla4ednRurFcEJdpi1vNAABwWEketHgSpT/E1Ja5npqQwFN+96/WgP2/gKOu74Lg9fQyrriCwPv7Xc=,iv:ta5zwJNsRgY91a20av2T95ODzhEE+iXoPP0mlBgoDSg=,tag:w9D83JAPhS5upFBmrK8tVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
