apiVersion: v1
kind: Secret
metadata:
    name: traefik-sso
    namespace: traefik
stringData:
    PROVIDERS_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:YyeFIm7UlqtAph9De+YQTfLIkf5S2mGyRS7MYx4ECWEjhHzQaHT4LI38IzUR2LpCSAp0hLiO6YVKjzeY88XssHVcFFIuGqik,iv:Lc0QtFL7QgQOsapGxkv3a1bQQTrwuIbEFNlWYGf895Q=,tag:pXqQEMwmBEbF6DyczBEnhg==,type:str]
    PROVIDERS_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:oky1l2Y1Oh2Yo6Bxj6c15Yp1i4j0xFbrDL3qlrkNRuFPMBQ=,iv:IP+Xowi2saR4xiG9kTOe1O01QZeVimzTMlYQ25Xs/6M=,tag:pbzVCNgzE+5Ksslb5oX9Iw==,type:str]
    SECRET: ENC[AES256_GCM,data:UAgIeMVX2jk4W8ywkxDnBj4EPDu85FK7ATumuTjIb7c=,iv:BZtRpYdmtxwLe9ku0Ka2nkm3ctv/sCcHlVLHC2ewRDE=,tag:FzS6AvZZwt5R8u5RGmO63w==,type:str]
    WHITELIST: ENC[AES256_GCM,data:O8+9vAY/6uOYuzeP29luspuE5NaFv1kJBugTlHeYZSo5lzxtZF36p+FA,iv:VIDFNSO5DWFKhwMKrov1UVTxG2l/nsWe1Ap0IJZPaLM=,tag:XloM3ZbhgrHyZAjgeSliwg==,type:str]
    COOKIE_DOMAIN: ENC[AES256_GCM,data:QB/2FK5L/w==,iv:aRDuOr98OQIooQMe/5WdRMwWWJERkY1QyO4p3IHuxd8=,tag:JKu6kGv87ErECG8po3MDfw==,type:str]
    AUTH_HOST: ENC[AES256_GCM,data:gl0UQYDeeQ==,iv:TEIFPCkiY00bkcgaMUJwSQNHJEJWD7cmUPJPR+HHGRo=,tag:Lz+XvW0S6uMAlkfZI5DWig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rlrtsx9gye40ewemdenax4phnr4jz5r5rkujn2klvjfpyhpqsqxs6wwjxq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRTljdzljVjkyVEd0TDcw
            ckY5cnhWS1loZkdpUkpYaEE1UWhvQzlKcmxvCjI1NmhXQzFTR3ZUUnkrN1ozWUZM
            ZmNueDdHYVl2N2lDVXdvTmdrWk9ncVkKLS0tIFJMUy9jZjFCUzZmdzFWSGtBQ1Nt
            UzlMbXVtdDN3YXFSN3A2VzQ2Z2dienMKhbQLf1nU7fg9G5xrRrX8wp2Ylcu4c72D
            1XMaEZ/HZcvj8GKC4qC9by6Wt+Nt5iDrAEbPUKaONY2rpFLN9kSaHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T04:59:29Z"
    mac: ENC[AES256_GCM,data:uskSolayYT2HOMJiSdtk3gd08pMrRnAjVwiJn058CdLz2OkoSGY6Fkh1uenNIMsG6eSls8PN0PNtmB+AfYi9lDFi5LpeabgcEfHTarQOixmE4a/CPvYy81moMIOS3n3M071r9t/XmQxzJXLRr5l9oAOlhaZcHwM9HZkBWC3hWS0=,iv:xvvHlZgWnZMCc+OI9ULKAnw3BBOlp/E+4QSooE0wt4U=,tag:zwTc/jMa0K78KHtdR2F1Wg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
