k3s_release_version: "v1.22.4+k3s1"

k3s_etcd_datastore: true

k3s_agent:
  node-ip: "{{ ansible_host }}"
  kubelet-arg:
    - "feature-gates=GracefulNodeShutdown=true"
    - "feature-gates=MixedProtocolLBService=true"
