---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cowboysysop-charts
  namespace: flux-system
spec:
  interval: 4h
  url: https://cowboysysop.github.io/charts/
  timeout: 3m
