---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: k8s-at-home-charts
  namespace: flux-system
spec:
  interval: 4h
  url: https://jupyterhub.github.io/helm-chart/
  timeout: 3m
