apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      hostNetwork: true
      containers:
        - name: server
          image: ghcr.io/hef/tauri-app/server:1.20.0 # {"$imagepolicy": "flux-system:server"}
          env:
            - name: RUST_BACKTRACE
              value: "full"
            - name: RUST_LOG
              value: "info"
          envFrom:
            - secretRef:
                name: server
          ports:
            - containerPort: 80
              hostPort: 80
              name: external
