apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ghcr.io/hef/tauri-app/server:1.9.2 # {"$imagepolicy": "flux-system:server"}
          envFrom:
            - secretRef:
                name: server
          ports:
            - containerPort: 4001
              hostPort: 4001
              name: external
