---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: server
  namespace: flux-system
spec:
  image: ghcr.io/hef/tauri-app/server
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: server
    namespace: flux-system
  policy:
    semver:
      range: '>=1.0.0'
