apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: server
  annotations:
    external-dns.alpha.kubernetes.io/endpoints-type: HostIP
    external-dns.alpha.kubernetes.io/hostname: server.hef.wtf
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  selector:
    app: server
  ports:
    - name: external
      port: 80
  clusterIP: None
