---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 15m
  chart:
    spec:
      chart: dex
      sourceRef:
        kind: HelmRepository
        name: dex-charts
        namespace: flux-system
  values:
    annotations:
      secret.reloader.stakater.com/reload: "dex-secrets"
    envFrom:
      - secretRef:
          name: dex-secrets
    config:
      issuer: https://dex.hef.wtf
      storage:
        type: memory
      connectors:
        - type: google
          id: google
          name: Google
          config:
            clientID: $GOOGLE_CLIENT_ID
            clientSecret: $GOOGLE_CLIENT_SECRET
            redirectURI: https://dex.hef.wtf/callback
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: dex.hef.wtf
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: dex.hef.wtf-tls
          hosts:
           - dex.hef.wtf
