apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: ${LETSENCRYPT_ACCOUNT}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            email: ${LETSENCRYPT_ACCOUNT}
            apiTokenSecretRef:
              name: secrets
              key: cloudflare_api_token