apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: ${LETSENCRYPT_ACCOUNT}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: ${LETSENCRYPT_ACCOUNT}
            apiTokenSecretRef:
              name: secrets
              key: cloudflare_api_token
