---
# https://www.voip-info.org/forum/threads/cloudatcost-debian-install-not-using-all-diskspace.19283/post-120957
# https://panel.cloudatcost.com/download/zang-debian.sh
# https://panel.cloudatcost.com/download/zang-ubuntu18.sh
- hosts:
    - master
    - worker
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Remove Swap from fstab
      ansible.posix.mount:
        path: none
        fstype: swap
        state: absent
    - name: Disable Swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0
    - name: remove swap LV
      community.general.lvol:
        vg: ubuntu-vg
        lv: swap_1
        force: yes
        state: absent
    - name: create sda2
      community.general.parted:
        device: /dev/sda
        number: 2
        flags: [lvm]
        state: present
        # part_start: "{{sda_info.partitions[0].end}}s" this needs to be +1
        part_start: "20969472s" # lol
        part_end: "100%"
        resize: true
    - name: Resize Volume Group /dev/ubuntu-vg
      community.general.lvg:
        vg: ubuntu-vg
        pvs: /dev/sda1,/dev/sda2
        pvresize: true
    - name: Resize /dev/ubuntu-vg/root
      community.general.lvol:
        vg: ubuntu-vg
        lv: root
        size: +100%FREE
        resizefs: true
    - name: remove C@C user "user"
      ansible.builtin.user:
        name: user
        state: "absent"
        remove: true
    - name: blacklist floppy
      ansible.builtin.copy:
        dest: /etc/modprobe.d/blacklist-floppy.conf
        content: "blacklist floppy"
      register: blacklist_floppy
    - name: update-initramfs
      ansible.builtin.command:
        cmd: update-initramfs -u
      when: blacklist_floppy.changed
    - name: unload floppy module
      community.general.modprobe:
        name: floppy
        state: absent
