---
- hosts:
    - master
    - worker
  gather_facts: true
  any_errors_fatal: true
  collections:
    - devsec.hardening
  roles:
    - ubuntu
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  vars:
    sysctl_overwrite:
      net.ipv4.ip_forward: 1
    ssh_permit_root_login: 'without-password'
    sftp_enabled: true
