---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 10.20.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  values:
    deployment:
      replicas: 2
      #dnsPolicy: ClusterFirstWithHostNet
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
      - "--entrypoints.websecure.http.middlewares=traefik-google-sso@kubernetescrd"
      - "--entrypoints.websecure.http.middlewares=traefik-error-pages@kubernetescrd"
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
    additionalArguments:
#    tlsOptions:
#      default:
#        # Only allow Cloudfront to reach us
#        clientAuth:
#          secretNames:
#            - secret-ca
#          clientAuthType: RequireAndVerifyClientCert
    service:
      enabled: true
      type: LoadBalancer
    #hostNetwork: true
    resources:
      requests:
        memory: 100Mi
        cpu: 500m
      limits:
        memory: 500Mi
