apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-sso
  labels:
    app: traefik-sso
  annotations:
    secret.reloader.stakater.com/reload: "traefik-sso"
spec:
  template:
    metadata:
      labels:
        app: traefik-sso
    spec:
      containers:
        - name: traefik-sso
          image: thomseddon/traefik-forward-auth:2
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: traefik-sso
          env:
            - name: LOG_LEVEL
              value: debug
            - name: COOKIE_DOMAIN
              value: hef.wtf
          ports:
            - containerPort: 4181
  selector:
    matchLabels:
      app: traefik-sso
