apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: error-pages
  template:
    metadata:
      labels:
        app: error-pages
    spec:
      containers:
        - name: error-pages
          image: ghcr.io/tarampampam/error-pages:2.16.0
          env:
            - name: TEMPLATE_NAME
              value: ghost
          ports:
            - containerPort: 8080
              name: http
