---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: 1.9.4
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  dependsOn:
    - name: rook-ceph
  values:
    cephClusterSpec:
      dashboard:
        enabled: true
        #urlPrefix: "/"
        ssl: false
    ingress:
      dashboard:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "chess-rook"
        host:
          name: rook.hef.sh
          path: "/"
