---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.2.4
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    defaultSettings:
      defaultDataLocality: "best-effort"
      replicaAutoBalance: "best-effort"
    ingress:
      enabled: true
      host: longhorn.hef.wtf
