---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.3.3
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    defaultSettings:
      defaultDataLocality: "best-effort"
      replicaAutoBalance: "best-effort"
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-google-sso@kubernetescrd
      enabled: true
      host: longhorn.hef.wtf
