---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  interval: 15m
  chart:
    spec:
      chart: jupyterhub
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: jupyterhub-charts
        namespace: flux-system
