---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 15m
  chart:
    spec:
      chart: vault
      version: 1.10.3
      sourceRef:
        kind: HelmRepository
        name: hashicorp-charts
        namespace: flux-system
