---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 15m
  chart:
    spec:
      chart: vault
      version: 0.20.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp-charts
        namespace: flux-system
  values:
    server:
      standalone:
        enabled: false
      ha:
        enabled: true
        raft:
          enabled: true
          setNodeId: true
      ingress:
        enabled: true
        hosts:
          - host: vault.hef.wtf
            paths: []
