apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - cluster
  - namespace.yaml
  - operator
  #- https://raw.githubusercontent.com/rook/rook/master/deploy/examples/toolbox.yaml
