---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoami
  namespace: whoami
spec:
  interval: 15m
  chart:
    spec:
      chart: whoami
      sourceRef:
        kind: HelmRepository
        name: cowboysysop-charts
        namespace: flux-system
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: whoami.hef.sh
          paths:
            - "/"
      tls:
        - secrename: whoami.hef.sh-tls
          hosts:
            - whoami.hef.sh
