---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: foundry
  namespace: foundry
spec:
  interval: 5m
  chart:
    spec:
      chart: foundryvtt
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    envFrom:
      - secretRef:
          name: foundry-secrets
    ingress:
      main:
        enabled: true
        hosts:
          - host: foundry.hef.wtf
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        existingClaim: foundry-data
