---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-data
  namespace: foundry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
