apiVersion: v1
kind: Secret
metadata:
    name: foundry-secrets
    namespace: foundry
stringData:
    FOUNDRY_USERNAME: ENC[AES256_GCM,data:EWd1,iv:0h3Gos0/HBLGcu+0Py64ciweMxCiaZWoXSVDaUpWq+E=,tag:2lF5e3dCVyV6Hmv1qNOXwg==,type:str]
    FOUNDRY_PASSWORD: ENC[AES256_GCM,data:/OL+O8FxxaSqyH3XldKz,iv:IeMeP5QvsiZ0QyNutZ9t/VJBUWL/icAnbjQV2cxmyeI=,tag:beQsHXML+1xCE/OozpWsUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rlrtsx9gye40ewemdenax4phnr4jz5r5rkujn2klvjfpyhpqsqxs6wwjxq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYzJFLzZ0ODlEZzEyQTJm
            ZUNKd3ZOeFJ3MnRreFV4Zk42Y25raS9ubXlRCklFcXphZ0JUeUtMcVZoWDVuR3cv
            cU9hekNSTGN5ZE1MV0N6VlMzUDltOGcKLS0tIEdPSUFQUm9ZMkt1Z0lVL1NJaHQ2
            MzBXQnVJcEI1Q1IyYTJHamtDSmdENnMKSVHNt5e0X2fDD7YhtPBGuJPNOKb0TQOb
            gWn86sQIJZeoz7EVmDCNsuEdmg4tWYjqK1LD/hu2/orTRNXzC6dYvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-31T03:13:25Z"
    mac: ENC[AES256_GCM,data:Njl4cT3ACMWkL+AygXLv2iUXZA0cyyE6WT44afLHy+g6suggOo5ridtSUOPckOgArDAqw3PAQtklNihMoekWutCYZGRHE6fLL8euFVw2Uo9p24PBN3SlAqzHqZEzKUE8Gsett1NGWoolY4gMT5nCRU5hpQE3tOLC8g3SzqdTyl4=,iv:8rKDtuo4Poz799hQh9kLF7FkioRJwAOcy0ZRs//w1d0=,tag:zYOpZ9trSnjceoIN8aLxgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
