apiVersion: v1
kind: Secret
metadata:
    name: foundry-secrets
    namespace: foundry
stringData:
    FOUNDRY_USERNAME: ENC[AES256_GCM,data:acfK,iv:OztTWvNWNOLlNJiBRJz4NZ8zZH5CBq4WJmW96QhHKug=,tag:nKDgJ+XqppgDctwDN9SHiQ==,type:str]
    FOUNDRY_PASSWORD: ENC[AES256_GCM,data:PN4F0hsFiFo1kxC1Z0iY,iv:7+J+1l9jmjI9ZNTG0cGH4uJc0ogv7Zt8UsgBmxLWKYc=,tag:TfGQuILBH3dAXoSppCNPFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-14T19:19:13Z"
    mac: ENC[AES256_GCM,data:PbJxNDe7v52/l9FYTH0Cw+pkhCTTDVh1XahpsOukAqr4aDqFTR/DUQnZH1FAY+xw7UJ8obYPMF0mSZ3bP1zGc6pdI3uirYuIi3wRtOcweKOBZsbpBVgnpo3CprMgDnM9AANrS2Ox/ZYGuh7fwzaeG0Onf4HbJjRbfGNlW3CD6BM=,iv:kZyQzilwwskISmGY5T3ysz0o167kOIzelLJmPq526MY=,tag:n3IKm4s7pQHcvijSRO5MIQ==,type:str]
    pgp:
        - created_at: "2021-12-14T19:19:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6gaWJekoI7XARAA76HnnRz5VbtMPypprGSAIWrsfNuP9FdDu8/CjinRknNh
            /t/y/puC+EmWJdM2xqWtNN3BtZNkiEwknHPp/YcLMTe8OI7TwQnISWKRw34oLtkS
            i85vytVGF2XjreXbj0kDj2QiZL1ilL5uw/1KB+iky1mL77fA8pZaETjeTRZiU7bz
            dX9uUIHX8HrvvCac8RhAnhaLNMkivzIKfOwzx0br3bGaQUea5XyiuVk+0Gadwuu0
            +uByMhoH8xkWfAPteBBAj+DS57WTyj51Xb5hX48ma5xBr59yVeGDyHQvJHf4OXDH
            Avqq1fLJKNtAZpjPjn8MyfwFOB6+5SiG/yGPjZqTqM+zMbGSMqGD9N/ZnSAnGrOC
            /ngVOxidxXtBHHJYb5tq8pPk9TJwhpQmVnNJc3WuPHG6fe6nCqmLMN22xZbMpWj/
            wOIPH63/J6gIIpgf2ARC6A0mb6llNHw7AJZAFks0/g0mf9N/9bIN1xW+kOAGKP1S
            xRz3SCi/w054n6KFY1NTMjv5iMuLcDolDhmP2td1+oUK3Rwil4CMrpf61+6hrHUy
            SW1m7ifb09MGvLgGZ/G0wBMM73ZThKytDus6caBHjKuaPDeVKYMY5Fvvxu+2JLsP
            a+xddrwzuLj2+PeIsO0IdhRueaLjR+fFY7ZoM2NdrcyiM1nDGTK88mzqlaMcLt7U
            aAEJAhDbaQM4V8E08/PRCdYQnAEXsK84iS7mri1Q+/WK+4Os2n8SEbpmXJZjQKir
            1eOiivs6N9kzvTXsvzh1gp3T3XBO9VIzebp7N+x1RVBgaDu9Y+121B/rFlLKKr3f
            lFrsDfhG/Wxo
            =2l+W
            -----END PGP MESSAGE-----
          fp: 06B57C420823EFD542A57D506F61683B2AA56450
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
