apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: foundry
  namespace: foundry
spec:
  selector:
    matchLabels:
      app: foundry
  template:
    metadata:
      labels:
        app: foundry
    spec:
      containers:
        - name: foundryvtt
          image: felddy/foundryvtt:10.263.0
          envFrom:
            - secretRef:
                name: foundry-secrets
          env:
            - name: FOUNDRY_HOSTNAME
              value: foundry.hef.wtf
            - name: FOUNDRY_PROXY_SSL
              value: "true"
            - name: FOUNDRY_PROXY_PORT
              value: "443"
          ports:
            - containerPort: 30000
              name: http
          volumeMounts:
            - mountPath: /data
              name: data
  serviceName: foundry
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
